/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OngoingCareRouteImport } from './routes/ongoing-care'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as AuthenticatedProviderRouteImport } from './routes/_authenticated/provider'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminServiceAreasRouteImport } from './routes/admin.service-areas'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ProvidersApplyRouteImport } from './routes/providers.apply'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAccountHomeCareRouteImport } from './routes/_authenticated/account.home-care'
import { Route as AuthenticatedAccountPaymentsRouteImport } from './routes/_authenticated/account.payments'
import { Route as AuthenticatedAccountServicesRouteImport } from './routes/_authenticated/account.services'
import { Route as AuthenticatedProviderIndexRouteImport } from './routes/_authenticated/provider.index'
import { Route as AuthenticatedProviderAccountRouteImport } from './routes/_authenticated/provider.account'
import { Route as AuthenticatedProviderCareRouteImport } from './routes/_authenticated/provider.care'
import { Route as AuthenticatedProviderEarningsRouteImport } from './routes/_authenticated/provider.earnings'
import { Route as AuthenticatedProviderJobsRouteImport } from './routes/_authenticated/provider.jobs'
import { Route as AuthenticatedProviderPageRouteImport } from './routes/_authenticated/provider.page'
import { Route as AuthenticatedProviderScheduleRouteImport } from './routes/_authenticated/provider.schedule'
import { Route as AuthenticatedProviderServicesRouteImport } from './routes/_authenticated/provider.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingCareRoute = OngoingCareRouteImport.update({
  id: '/ongoing-care',
  path: '/ongoing-care',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderRoute = AuthenticatedProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceAreasRoute = AdminServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const ProvidersApplyRoute = ProvidersApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ProvidersRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountHomeCareRoute =
  AuthenticatedAccountHomeCareRouteImport.update({
    id: '/account/home-care',
    path: '/account/home-care',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountPaymentsRoute =
  AuthenticatedAccountPaymentsRouteImport.update({
    id: '/account/payments',
    path: '/account/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountServicesRoute =
  AuthenticatedAccountServicesRouteImport.update({
    id: '/account/services',
    path: '/account/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderIndexRoute =
  AuthenticatedProviderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderAccountRoute =
  AuthenticatedProviderAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderCareRoute =
  AuthenticatedProviderCareRouteImport.update({
    id: '/care',
    path: '/care',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderEarningsRoute =
  AuthenticatedProviderEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderJobsRoute =
  AuthenticatedProviderJobsRouteImport.update({
    id: '/jobs',
    path: '/jobs',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderPageRoute =
  AuthenticatedProviderPageRouteImport.update({
    id: '/page',
    path: '/page',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderScheduleRoute =
  AuthenticatedProviderScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)
const AuthenticatedProviderServicesRoute =
  AuthenticatedProviderServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedProviderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/ongoing-care': typeof OngoingCareRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/provider': typeof AuthenticatedProviderRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRoute
  '/p/$slug': typeof PSlugRoute
  '/providers/apply': typeof ProvidersApplyRoute
  '/services/$service': typeof ServicesServiceRoute
  '/admin/': typeof AdminIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/account/home-care': typeof AuthenticatedAccountHomeCareRoute
  '/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/account/services': typeof AuthenticatedAccountServicesRoute
  '/provider/account': typeof AuthenticatedProviderAccountRoute
  '/provider/care': typeof AuthenticatedProviderCareRoute
  '/provider/earnings': typeof AuthenticatedProviderEarningsRoute
  '/provider/jobs': typeof AuthenticatedProviderJobsRoute
  '/provider/page': typeof AuthenticatedProviderPageRoute
  '/provider/schedule': typeof AuthenticatedProviderScheduleRoute
  '/provider/services': typeof AuthenticatedProviderServicesRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/provider/': typeof AuthenticatedProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/ongoing-care': typeof OngoingCareRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRoute
  '/p/$slug': typeof PSlugRoute
  '/providers/apply': typeof ProvidersApplyRoute
  '/services/$service': typeof ServicesServiceRoute
  '/admin': typeof AdminIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/account/home-care': typeof AuthenticatedAccountHomeCareRoute
  '/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/account/services': typeof AuthenticatedAccountServicesRoute
  '/provider/account': typeof AuthenticatedProviderAccountRoute
  '/provider/care': typeof AuthenticatedProviderCareRoute
  '/provider/earnings': typeof AuthenticatedProviderEarningsRoute
  '/provider/jobs': typeof AuthenticatedProviderJobsRoute
  '/provider/page': typeof AuthenticatedProviderPageRoute
  '/provider/schedule': typeof AuthenticatedProviderScheduleRoute
  '/provider/services': typeof AuthenticatedProviderServicesRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/provider': typeof AuthenticatedProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/ongoing-care': typeof OngoingCareRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/_authenticated/provider': typeof AuthenticatedProviderRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRoute
  '/p/$slug': typeof PSlugRoute
  '/providers/apply': typeof ProvidersApplyRoute
  '/services/$service': typeof ServicesServiceRoute
  '/admin/': typeof AdminIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/account/home-care': typeof AuthenticatedAccountHomeCareRoute
  '/_authenticated/account/payments': typeof AuthenticatedAccountPaymentsRoute
  '/_authenticated/account/services': typeof AuthenticatedAccountServicesRoute
  '/_authenticated/provider/account': typeof AuthenticatedProviderAccountRoute
  '/_authenticated/provider/care': typeof AuthenticatedProviderCareRoute
  '/_authenticated/provider/earnings': typeof AuthenticatedProviderEarningsRoute
  '/_authenticated/provider/jobs': typeof AuthenticatedProviderJobsRoute
  '/_authenticated/provider/page': typeof AuthenticatedProviderPageRoute
  '/_authenticated/provider/schedule': typeof AuthenticatedProviderScheduleRoute
  '/_authenticated/provider/services': typeof AuthenticatedProviderServicesRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/provider/': typeof AuthenticatedProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/login'
    | '/ongoing-care'
    | '/providers'
    | '/provider'
    | '/admin/customers'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/service-areas'
    | '/admin/services'
    | '/p/$slug'
    | '/providers/apply'
    | '/services/$service'
    | '/admin/'
    | '/providers/'
    | '/services/'
    | '/account/home-care'
    | '/account/payments'
    | '/account/services'
    | '/provider/account'
    | '/provider/care'
    | '/provider/earnings'
    | '/provider/jobs'
    | '/provider/page'
    | '/provider/schedule'
    | '/provider/services'
    | '/account/'
    | '/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/login'
    | '/ongoing-care'
    | '/admin/customers'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/service-areas'
    | '/admin/services'
    | '/p/$slug'
    | '/providers/apply'
    | '/services/$service'
    | '/admin'
    | '/providers'
    | '/services'
    | '/account/home-care'
    | '/account/payments'
    | '/account/services'
    | '/provider/account'
    | '/provider/care'
    | '/provider/earnings'
    | '/provider/jobs'
    | '/provider/page'
    | '/provider/schedule'
    | '/provider/services'
    | '/account'
    | '/provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/book'
    | '/login'
    | '/ongoing-care'
    | '/providers'
    | '/_authenticated/provider'
    | '/admin/customers'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/service-areas'
    | '/admin/services'
    | '/p/$slug'
    | '/providers/apply'
    | '/services/$service'
    | '/admin/'
    | '/providers/'
    | '/services/'
    | '/_authenticated/account/home-care'
    | '/_authenticated/account/payments'
    | '/_authenticated/account/services'
    | '/_authenticated/provider/account'
    | '/_authenticated/provider/care'
    | '/_authenticated/provider/earnings'
    | '/_authenticated/provider/jobs'
    | '/_authenticated/provider/page'
    | '/_authenticated/provider/schedule'
    | '/_authenticated/provider/services'
    | '/_authenticated/account/'
    | '/_authenticated/provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  OngoingCareRoute: typeof OngoingCareRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  PSlugRoute: typeof PSlugRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing-care': {
      id: '/ongoing-care'
      path: '/ongoing-care'
      fullPath: '/ongoing-care'
      preLoaderRoute: typeof OngoingCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provider': {
      id: '/_authenticated/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof AuthenticatedProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-areas': {
      id: '/admin/service-areas'
      path: '/service-areas'
      fullPath: '/admin/service-areas'
      preLoaderRoute: typeof AdminServiceAreasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/providers/apply': {
      id: '/providers/apply'
      path: '/apply'
      fullPath: '/providers/apply'
      preLoaderRoute: typeof ProvidersApplyRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/home-care': {
      id: '/_authenticated/account/home-care'
      path: '/account/home-care'
      fullPath: '/account/home-care'
      preLoaderRoute: typeof AuthenticatedAccountHomeCareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/payments': {
      id: '/_authenticated/account/payments'
      path: '/account/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AuthenticatedAccountPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/services': {
      id: '/_authenticated/account/services'
      path: '/account/services'
      fullPath: '/account/services'
      preLoaderRoute: typeof AuthenticatedAccountServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/': {
      id: '/_authenticated/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof AuthenticatedProviderIndexRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/provider/account': {
      id: '/_authenticated/provider/account'
      path: '/account'
      fullPath: '/provider/account'
      preLoaderRoute: typeof AuthenticatedProviderAccountRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/provider/care': {
      id: '/_authenticated/provider/care'
      path: '/care'
      fullPath: '/provider/care'
      preLoaderRoute: typeof AuthenticatedProviderCareRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/provider/earnings': {
      id: '/_authenticated/provider/earnings'
      path: '/earnings'
      fullPath: '/provider/earnings'
      preLoaderRoute: typeof AuthenticatedProviderEarningsRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/provider/jobs': {
      id: '/_authenticated/provider/jobs'
      path: '/jobs'
      fullPath: '/provider/jobs'
      preLoaderRoute: typeof AuthenticatedProviderJobsRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/provider/page': {
      id: '/_authenticated/provider/page'
      path: '/page'
      fullPath: '/provider/page'
      preLoaderRoute: typeof AuthenticatedProviderPageRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/provider/schedule': {
      id: '/_authenticated/provider/schedule'
      path: '/schedule'
      fullPath: '/provider/schedule'
      preLoaderRoute: typeof AuthenticatedProviderScheduleRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
    '/_authenticated/provider/services': {
      id: '/_authenticated/provider/services'
      path: '/services'
      fullPath: '/provider/services'
      preLoaderRoute: typeof AuthenticatedProviderServicesRouteImport
      parentRoute: typeof AuthenticatedProviderRoute
    }
  }
}

interface AuthenticatedProviderRouteChildren {
  AuthenticatedProviderAccountRoute: typeof AuthenticatedProviderAccountRoute
  AuthenticatedProviderCareRoute: typeof AuthenticatedProviderCareRoute
  AuthenticatedProviderEarningsRoute: typeof AuthenticatedProviderEarningsRoute
  AuthenticatedProviderJobsRoute: typeof AuthenticatedProviderJobsRoute
  AuthenticatedProviderPageRoute: typeof AuthenticatedProviderPageRoute
  AuthenticatedProviderScheduleRoute: typeof AuthenticatedProviderScheduleRoute
  AuthenticatedProviderServicesRoute: typeof AuthenticatedProviderServicesRoute
  AuthenticatedProviderIndexRoute: typeof AuthenticatedProviderIndexRoute
}

const AuthenticatedProviderRouteChildren: AuthenticatedProviderRouteChildren = {
  AuthenticatedProviderAccountRoute: AuthenticatedProviderAccountRoute,
  AuthenticatedProviderCareRoute: AuthenticatedProviderCareRoute,
  AuthenticatedProviderEarningsRoute: AuthenticatedProviderEarningsRoute,
  AuthenticatedProviderJobsRoute: AuthenticatedProviderJobsRoute,
  AuthenticatedProviderPageRoute: AuthenticatedProviderPageRoute,
  AuthenticatedProviderScheduleRoute: AuthenticatedProviderScheduleRoute,
  AuthenticatedProviderServicesRoute: AuthenticatedProviderServicesRoute,
  AuthenticatedProviderIndexRoute: AuthenticatedProviderIndexRoute,
}

const AuthenticatedProviderRouteWithChildren =
  AuthenticatedProviderRoute._addFileChildren(
    AuthenticatedProviderRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProviderRoute: typeof AuthenticatedProviderRouteWithChildren
  AuthenticatedAccountHomeCareRoute: typeof AuthenticatedAccountHomeCareRoute
  AuthenticatedAccountPaymentsRoute: typeof AuthenticatedAccountPaymentsRoute
  AuthenticatedAccountServicesRoute: typeof AuthenticatedAccountServicesRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProviderRoute: AuthenticatedProviderRouteWithChildren,
  AuthenticatedAccountHomeCareRoute: AuthenticatedAccountHomeCareRoute,
  AuthenticatedAccountPaymentsRoute: AuthenticatedAccountPaymentsRoute,
  AuthenticatedAccountServicesRoute: AuthenticatedAccountServicesRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminServiceAreasRoute: typeof AdminServiceAreasRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminServiceAreasRoute: AdminServiceAreasRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProvidersRouteChildren {
  ProvidersApplyRoute: typeof ProvidersApplyRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersApplyRoute: ProvidersApplyRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  OngoingCareRoute: OngoingCareRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  PSlugRoute: PSlugRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
